[general]
theme = 'base16'
theme_variant = 'material'

[editor]
linenos = 'relative'
hard_wrap = true
wrap_width = 80

[frontend.terminal]
256color = true

[plugins]
update_on_start = true

[plugins.toml]
source = 'https://github.com/Notavi-Editor/toml'
